export const PERMISSIONS = [
  "cases:read",
  "cases:write",
  "cases:delete",
  "clients:read",
  "clients:write",
  "clients:delete",
  "documents:read",
  "documents:write",
  "documents:delete",
  "billing:read",
  "billing:write",
  "billing:approve",
  "time:read",
  "time:write",
  "time:approve",
  "calendar:read",
  "calendar:write",
  "emails:read",
  "emails:write",
  "emails:send",
  "approvals:view",
  "approvals:decide",
  "users:read",
  "users:write",
  "users:invite",
  "firm:settings",
  "firm:billing",
  "reports:view",
  "reports:export",
  "ai:use",
  "ai:configure",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const DEFAULT_ROLE_PERMISSIONS: Record<"admin" | "fee_earner", Permission[]> = {
  admin: [...PERMISSIONS],
  fee_earner: [
    "cases:read",
    "cases:write",
    "clients:read",
    "clients:write",
    "documents:read",
    "documents:write",
    "emails:read",
    "emails:write",
    "emails:send",
    "calendar:read",
    "calendar:write",
    "time:read",
    "time:write",
    "billing:read",
    "approvals:view",
    "ai:use",
  ],
};
